-- done
INSERT INTO items (category_id, item_name)
VALUES
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Apple'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Banana'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Orange'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Mandarin'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Grapefruit'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Lemon'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Lime'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Strawberries'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Blueberries'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Raspberries'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Blackberries'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Grapes'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Watermelon'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Cantaloupe'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Honeydew'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Pineapple'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Mango'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Papaya'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Kiwi'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Peach'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Nectarine'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Plum'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Cherry'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Pear'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Apricot'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Pomegranate'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Cranberries'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Fig'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Date'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Guava'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Passion Fruit'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Lychee'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Dragon Fruit'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Jackfruit'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Starfruit'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Persimmon'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Coconut'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Plantain'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Tangerine'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Clementine'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Avocado'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Tomato'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Cherry Tomato'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Grape Tomato'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Roma Tomato'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Beefsteak Tomato'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Cucumber'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'English Cucumber'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Zucchini'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Yellow Squash'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Eggplant'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Bell Pepper'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Red Bell Pepper'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Green Bell Pepper'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Jalapeno Pepper'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Serrano Pepper'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Habanero Pepper'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Poblano Pepper'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Chili Pepper'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Onion'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Yellow Onion'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Red Onion'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'White Onion'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Green Onion'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Garlic'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Shallot'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Leek'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Ginger'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Potato'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Russet Potato'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Red Potato'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Yukon Gold Potato'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Sweet Potato'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Carrot'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Baby Carrots'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Celery'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Radish'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Beet'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Turnip'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Parsnip'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Broccoli'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Cauliflower'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Brussels Sprouts'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Cabbage'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Red Cabbage'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Bok Choy'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Kale'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Spinach'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Romaine Lettuce'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Iceberg Lettuce'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Arugula'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Swiss Chard'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Asparagus'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Green Beans'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Peas'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Corn'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Mushrooms'),
((SELECT category_id FROM categories WHERE category_name = 'Produce'), 'Portobello Mushrooms');

INSERT INTO items (category_id, item_name)
VALUES
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Whole Chicken'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Chicken Wings'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Chicken Drumsticks'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Ground Chicken'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Chicken Tenderloins'),

((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Ribeye Steak'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Sirloin Steak'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'T Bone Steak'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Filet Mignon'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Beef Chuck Roast'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Beef Brisket'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Beef Short Ribs'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Ground Turkey'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Turkey Breast'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Turkey Sausage'),

((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Pork Tenderloin'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Pork Ribs'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Pork Shoulder'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Pork Belly'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Ground Pork'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Italian Sausage'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Breakfast Sausage'),

((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Hot Dogs'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Deli Ham'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Deli Turkey'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Pepperoni'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Salami'),

((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Cod Fillet'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Halibut'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Mahi Mahi'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Catfish'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Swordfish'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Trout'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Sardines'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Anchovies'),

((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Lobster Tail'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Crab Legs'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Clams'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Mussels'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Scallops'),

((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Lamb Chops'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Lamb Shank'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Veal Cutlets'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Bison Steak'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Duck Breast'),
((SELECT category_id FROM categories WHERE category_name = 'Meat and Seafood'), 'Cornish Hen');

INSERT INTO items (category_id, item_name)
VALUES
((SELECT category_id FROM categories WHERE category_name = 'Dairy'), 'Whole Milk'),
((SELECT category_id FROM categories WHERE category_name = 'Dairy'), '2 Percent Milk'),
((SELECT category_id FROM categories WHERE category_name = 'Dairy'), 'Half and Half'),
((SELECT category_id FROM categories WHERE category_name = 'Dairy'), 'Butter'),
((SELECT category_id FROM categories WHERE category_name = 'Dairy'), 'Sour Cream'),
((SELECT category_id FROM categories WHERE category_name = 'Dairy'), 'Cream Cheese'),
((SELECT category_id FROM categories WHERE category_name = 'Dairy'), 'Cheddar Cheese'),
((SELECT category_id FROM categories WHERE category_name = 'Dairy'), 'Mozzarella Cheese'),
((SELECT category_id FROM categories WHERE category_name = 'Dairy'), 'Parmesan Cheese'),
((SELECT category_id FROM categories WHERE category_name = 'Dairy'), 'Greek Yogurt'),
((SELECT category_id FROM categories WHERE category_name = 'Dairy'), 'Eggs');

INSERT INTO items (category_id, item_name)
VALUES
((SELECT category_id FROM categories WHERE category_name = 'Bakery'), 'Sandwich Bread'),
((SELECT category_id FROM categories WHERE category_name = 'Bakery'), 'Whole Wheat Bread'),
((SELECT category_id FROM categories WHERE category_name = 'Bakery'), 'Bagels'),
((SELECT category_id FROM categories WHERE category_name = 'Bakery'), 'English Muffins'),
((SELECT category_id FROM categories WHERE category_name = 'Bakery'), 'Tortillas'),
((SELECT category_id FROM categories WHERE category_name = 'Bakery'), 'Pita Bread'),
((SELECT category_id FROM categories WHERE category_name = 'Bakery'), 'Hamburger Buns'),
((SELECT category_id FROM categories WHERE category_name = 'Bakery'), 'Croissants'),
((SELECT category_id FROM categories WHERE category_name = 'Bakery'), 'Muffins'),
((SELECT category_id FROM categories WHERE category_name = 'Bakery'), 'Cinnamon Rolls');

INSERT INTO items (category_id, item_name)
VALUES

-- Rice & Grains
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'White Rice'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Brown Rice'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Jasmine Rice'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Basmati Rice'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Wild Rice'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Quinoa'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Couscous'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Bulgur'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Farro'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Barley'),

-- Pasta
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Spaghetti'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Penne'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Fusilli'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Linguine'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Macaroni'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Lasagna Noodles'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Angel Hair Pasta'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Whole Wheat Pasta'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Gluten Free Pasta'),

-- Flour & Baking
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'All Purpose Flour'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Bread Flour'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Cake Flour'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Self Rising Flour'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Cornmeal'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Baking Powder'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Baking Soda'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Active Dry Yeast'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Instant Yeast'),

-- Sugar & Sweeteners
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'White Sugar'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Brown Sugar'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Powdered Sugar'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Honey'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Maple Syrup'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Agave Nectar'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Molasses'),

-- Oils & Vinegars
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Olive Oil'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Vegetable Oil'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Canola Oil'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Sesame Oil'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Coconut Oil'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Apple Cider Vinegar'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'White Vinegar'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Balsamic Vinegar'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Red Wine Vinegar'),

-- Canned Vegetables
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Canned Corn'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Canned Peas'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Canned Green Beans'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Canned Carrots'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Canned Spinach'),

-- Canned Beans
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Black Beans'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Pinto Beans'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Kidney Beans'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Garbanzo Beans'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Lentils'),

-- Canned Tomatoes
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Canned Tomatoes'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Crushed Tomatoes'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Tomato Sauce'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Tomato Paste'),

-- Soups & Broths
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Chicken Broth'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Beef Broth'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Vegetable Broth'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Chicken Noodle Soup'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Tomato Soup'),

-- Sauces & Condiments
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Soy Sauce'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Hot Sauce'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Ketchup'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Mustard'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Mayonnaise'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Barbecue Sauce'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Teriyaki Sauce'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Worcestershire Sauce'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Peanut Butter'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Almond Butter'),

-- Breakfast Dry Goods
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Oats'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Granola'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Cornflakes'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Pancake Mix'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Waffle Mix'),

-- Dry Snacks
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Popcorn Kernels'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Nutty Trail Mix'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Raisins'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Dried Cranberries'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Chia Seeds'),
((SELECT category_id FROM categories WHERE category_name = 'Pantry Staples'), 'Flax Seeds');


INSERT INTO items (category_id, item_name)
VALUES
((SELECT category_id FROM categories WHERE category_name = 'Spices and Herbs'), 'Salt'),
((SELECT category_id FROM categories WHERE category_name = 'Spices and Herbs'), 'Black Pepper'),
((SELECT category_id FROM categories WHERE category_name = 'Spices and Herbs'), 'Garlic Powder'),
((SELECT category_id FROM categories WHERE category_name = 'Spices and Herbs'), 'Onion Powder'),
((SELECT category_id FROM categories WHERE category_name = 'Spices and Herbs'), 'Paprika'),
((SELECT category_id FROM categories WHERE category_name = 'Spices and Herbs'), 'Cumin'),
((SELECT category_id FROM categories WHERE category_name = 'Spices and Herbs'), 'Chili Powder'),
((SELECT category_id FROM categories WHERE category_name = 'Spices and Herbs'), 'Oregano'),
((SELECT category_id FROM categories WHERE category_name = 'Spices and Herbs'), 'Basil'),
((SELECT category_id FROM categories WHERE category_name = 'Spices and Herbs'), 'Cinnamon');

INSERT INTO items (category_id, item_name)
VALUES
((SELECT category_id FROM categories WHERE category_name = 'Beverages'), 'Bottled Water'),
((SELECT category_id FROM categories WHERE category_name = 'Beverages'), 'Sparkling Water'),
((SELECT category_id FROM categories WHERE category_name = 'Beverages'), 'Orange Juice'),
((SELECT category_id FROM categories WHERE category_name = 'Beverages'), 'Apple Juice'),
((SELECT category_id FROM categories WHERE category_name = 'Beverages'), 'Cola Soda'),
((SELECT category_id FROM categories WHERE category_name = 'Beverages'), 'Lemon Lime Soda'),
((SELECT category_id FROM categories WHERE category_name = 'Beverages'), 'Coffee'),
((SELECT category_id FROM categories WHERE category_name = 'Beverages'), 'Green Tea'),
((SELECT category_id FROM categories WHERE category_name = 'Beverages'), 'Black Tea'),
((SELECT category_id FROM categories WHERE category_name = 'Beverages'), 'Sports Drink');

INSERT INTO items (category_id, item_name)
VALUES
((SELECT category_id FROM categories WHERE category_name = 'Snacks'), 'Potato Chips'),
((SELECT category_id FROM categories WHERE category_name = 'Snacks'), 'Tortilla Chips'),
((SELECT category_id FROM categories WHERE category_name = 'Snacks'), 'Pretzels'),
((SELECT category_id FROM categories WHERE category_name = 'Snacks'), 'Popcorn'),
((SELECT category_id FROM categories WHERE category_name = 'Snacks'), 'Crackers'),
((SELECT category_id FROM categories WHERE category_name = 'Snacks'), 'Trail Mix'),
((SELECT category_id FROM categories WHERE category_name = 'Snacks'), 'Granola Bars'),
((SELECT category_id FROM categories WHERE category_name = 'Snacks'), 'Chocolate Bar'),
((SELECT category_id FROM categories WHERE category_name = 'Snacks'), 'Cookies'),
((SELECT category_id FROM categories WHERE category_name = 'Snacks'), 'Gummy Candy');

